# config.yaml
cookie:
  name: 'comparador_dian_cookie'
  key: 'tu_clave_secreta_aqui_debes_cambiarla_por_una_larga' 
  expiry_days: 30

credentials:
  usernames:
    # ⬇️ NUEVO USUARIO ⬇️
    CONTADORA: 
      email: "dolyblancogallo@gmail.com" # Puedes cambiar el email
      name: "Doly Blanco"     # Nombre a mostrar en la app
      password: "$2a$12$mu7x5nSi22.rsf1FajWN/e439H9FR.atvpO45hAPMyOWqK3Q8sC8."
